#!/usr/bin/env php
<?php
	require __DIR__.'/vendor/autoload.php';

	use Suphle\Console\CliRunner;

	use Suphle\Adapters\Console\SymfonyCli;

	use AllModules\PublishedModules;

	$runner = new CliRunner (

		new PublishedModules, new SymfonyCli("Suphle", "v2")
	);

	$runner->extractAvailableCommands()->setRootPath(__DIR__)

	->funnelToClient();

	$runner->awaitCommands();
?>