#!/usr/bin/env php
<?php
	require __DIR__.'/vendor/autoload.php';

	use Suphle\Console\CliRunnerAccessor;

	use AllModules\PublishedModules;

	(new CliRunnerAccessor(new PublishedModules))

	->forwardCommandsToRunner(__DIR__);
?>